[project]
name = "pytoningans"
version = "0.5.8"
description = "A PySide6 Desktop Pets App"
readme = "README.md"
authors = [{ name = "MetaDusk", email = "andredcxxv@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["pyside6>=6.11.2"]

[project.scripts]
pytoningans = "pytoningans:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
